-- =============================================================================
-- Ghost Repos v6: Extended date range + tighter noise filters
-- =============================================================================
-- This query is not fully saved — it was run interactively and the output
-- is in data/raw/bquxjob_412f814a_19d44cadf87.csv (999 rows).
--
-- Changes from v5:
--   1. Extended date range: 2025-01-01 to 2026-03-30 (covers 15 months
--      instead of the 2025-only window in v5)
--   2. Tightened a few noise filter thresholds based on patterns spotted in
--      the v5 output (e.g., some i18n-only repos and package-registry mirrors
--      that passed v5's filters)
--   3. Same single-pass activity_base CTE structure as v5
--   4. Same two-stage GitHub API verification pipeline (scripts/main.py)
--
-- The v6 BigQuery output hasn't been fully scored through the Python pipeline
-- yet. It's available in data/raw/ for future runs.
--
-- To re-run this against the current dataset, adapt the table suffix range:
--
-- FROM `githubarchive.day.*`
-- WHERE _TABLE_SUFFIX BETWEEN '20250101' AND '20260330'
--
-- Everything else (CTEs, filters, thresholds) is the same as v05 above.
-- =============================================================================
